server:
  port: 8080
  servlet:
    context-path: /west-city
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  logging:
    file: dev_profile_app.log
    path: ./log
    level:
      root: info
      org.springframework.web: DEBUG
      io.github.ireflux.westcitymall: DEBUG
  datasource:
    url: jdbc:mysql://192.168.31.108:3306/west_city_mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.31.108
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
fdfs:
  #连接超时
  connect-timout: 6000
  #读取超时
  so-timout: 10000
  #Tracte服务的ip和端口,多个可以用逗号隔开,或者通过nginx做一个负载均衡然后配置一个即可。
  tracker-list: 192.168.31.108:22122
  tracker_server: 192.168.31.108:22122